name: Cypress Tests

on: 
    push:
     #Trigger the build manually 
    workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      #If something fails it wouldn't stop the execution. It will continue the execution.
        fail-fast: false
        matrix: 
            browser: [chrome, edge, electron]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        # with:
        #   build: npm run build
        #   start: npm start+
        with: 
          browser: ${{ matrix.browser }}
          command: npx cypress run --browsers ${{ matrix.browser }} --reporter mochawesome --reporter-options reportDir=cypress/reports/${{ matrix.browser }}

      - name: Marge Mochawesome Reports
        run: npx mochaesome-merge cypress/reports/${{ matrix.browser }}/*.json > cypress/reports/${{ matrix.browser }}/merged-reports.json

      - name: Generate HTML Reports
        run: npx marge cypress/reports/${{ matrix.browser }}/ merged-reports.json --reportDir cypress/reports/${{ matrix.browser }} -f "${{ matrix.browser }}-report.html"

      - name: Upload HTML file
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report ${{ matrix.browser }}
          path: cypress/report/${{ matrix.browser }}

       